  name: Deploy to WordPress via SFTP

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      name: Deploy Plugin Files
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Deploy to WordPress via SFTP
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ${{ secrets.SFTP_HOST }}
            username: ${{ secrets.SFTP_USERNAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            port: ${{ secrets.SFTP_PORT }}
            protocol: ftps
            server-dir: ${{ secrets.SFTP_PATH }}
            exclude: |
              **/.git*
              **/.git*/**
              **/node_modules/**
              **/.github/**
              **/*.sh
              **/*.zip
              **/.DS_Store
              **/DEPLOYMENT.md
